defaults:
  date: "{{today}}"
  league: premier_league
  write_latest: true

tasks:
  - section: NEWS.TOP3
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - collector/curated/news/sky_sports_premier_league/premier_league/{{today}}/items.json

  - section: NEWS.TOP_AFRICAN_PLAYERS
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - collector/curated/news/sky_sports_premier_league/premier_league/{{today}}/items.json

  - section: GENERIC.INTRO_POSTMATCH
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest

  - section: OPINION.EXPERT_COMMENT
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - collector/curated/news/sky_sports_premier_league/premier_league/{{today}}/items.json

  - section: OPINION.DUO_EXPERTS
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - collector/curated/news/sky_sports_premier_league/premier_league/{{today}}/items.json

  - section: GENERIC.INTRO_DAILY
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
