defaults:
  date: "{{today}}"
  league: premier_league
  write_latest: true

tasks:
  - section: S.NEWS.TOP3.GENERIC
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - producer/scored/{{today}}/scored_enriched.jsonl

  - section: S.NEWS.TOP.AFRICAN.PLAYERS
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - producer/scored/{{today}}/scored_enriched.jsonl

  - section: S.OPINION.EXPERT.COMMENT
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - producer/scored/{{today}}/scored_enriched.jsonl

  - section: S.OPINION.DUO.EXPERTS
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - producer/scored/{{today}}/scored_enriched.jsonl
      
  - section: S.GENERIC.INTRO.POSTMATCH
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest

  - section: S.GENERIC.INTRO.DAILY
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest

  - section: S.NEWS.CLUB.HIGHLIGHT   # 🔥 ny sektion
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - producer/scored/{{today}}/scored_enriched.jsonl

  - section: S.STATS.DRIVER
    args:
      - --outdir
      - sections
      - --write-latest
