defaults:
  date: "{{today}}"
  league: premier_league
  write_latest: true

tasks:
  - section: S.NEWS.TOP3
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - producer/candidates/{{today}}/scored.jsonl

  - section: S.NEWS.TOP_AFRICAN_PLAYERS
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - producer/candidates/{{today}}/scored.jsonl

  - section: S.OPINION.EXPERT_COMMENT
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - producer/candidates/{{today}}/scored.jsonl

  - section: S.OPINION.DUO_EXPERTS
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - producer/candidates/{{today}}/scored.jsonl

  - section: S.GENERIC.INTRO_POSTMATCH
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest

  - section: S.GENERIC.INTRO_DAILY
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest

  - section: S.NEWS.CLUB_HIGHLIGHT   # 🔥 ny sektion
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - producer/candidates/{{today}}/scored.jsonl
