defaults:
  date: "{{today}}"
  league: premier_league
  write_latest: true

tasks:
  - section_code: S.NEWS.TOP3
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - producer/candidates/{{today}}/scored.jsonl

  - section_code: S.NEWS.TOP_AFRICAN_PLAYERS
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - producer/candidates/{{today}}/scored.jsonl
