# produce-job.yaml
type: Microsoft.App/job
apiVersion: 2023-05-01
name: afp-produce-job
location: westeurope
properties:
  configuration:
    triggerType: Manual   # Körs on-demand via ACA Job
    secrets:
      - name: afp-openai-secretkey
        value: ${AFP_OPENAI_SECRETKEY}
      - name: blob-container-sas-url
        value: ${BLOB_CONTAINER_SAS_URL}
      - name: azure-storage-account
        value: ${AZURE_STORAGE_ACCOUNT}
      - name: azure-container
        value: ${AZURE_CONTAINER}
  template:
    containers:
      - name: produce
        image: ghcr.io/<org>/<repo>:latest   # Overridas i GH Actions med :${{ github.sha }}
        env:
          - name: JOB_TYPE
            value: "produce"
          - name: JOB_ARGS
            value: >
              --section-code S.NEWS.TOP3
              --news https://<storageaccount>.blob.core.windows.net/afp/curated/news/guardian_football/premier_league/2025-08-29/items.json?<sas>
              --outdir /app/blob_out/produce
              --write-latest
          - name: LOG_LEVEL
            value: "INFO"
          - name: AFP_OPENAI_SECRETKEY
            secretRef: afp-openai-secretkey
          - name: BLOB_CONTAINER_SAS_URL
            secretRef: blob-container-sas-url
          - name: AZURE_STORAGE_ACCOUNT
            secretRef: azure-storage-account
          - name: AZURE_CONTAINER
            secretRef: azure-container
    restartPolicy: Never
