flowchart TD

    A[Collect (ACA Job, cron)]
    B[Warehouse Live (ACA Job)]
    C[Produce (ACA Job)]
    D[Assemble (ACA Job)]
    E[Render (ACA Job)]
    F[Mix (ACA Job)]
    G[Publish (ACA Job)]

    A --> B
    B --> C
    C --> D
    D --> E
    E --> F
    F --> G

    subgraph AzureContainerAppsJobs
        A
        B
        C
        D
        E
        F
        G
    end
