flowchart TD

  %% Data objects
  L[(Leagues.json)]
  S[(Seasons files)]
  M[(Match files)]
  H[(Player history)]
  PS[(Player stats)]
  PA[(Players Africa)]
  T[(Teams)]
  TR[(Transfers)]
  P[(Profiles)]
  MASTER[(Master players)]
  MH[(Merged history)]
  DRAFT[(Transfers draft)]
  CI[(Club index)]
  MISS[(Missing history)]
  SCAN[(Scan results)]

  %% Collect
  CL[collect_leagues] --> L
  L --> CS[collect_all_seasons]
  CS --> S

  CE1[collect_extract_fullseason] --> M
  CE2[collect_extract_weekly] --> M

  M --> CH[collect_player_history]
  M --> CP[collect_player_stats]
  M --> CA[collect_players_africa]
  M --> CT[collect_teams]

  CH --> H
  CP --> PS
  CA --> PA
  CT --> T

  CTR[collect_transfers] --> TR
  CPROF[collect_player_profiles] --> P

  %% Merge
  M1[merge_players_africa] --> MASTER
  M2[merge_africa_player_history] --> MH
  M2 --> MISS
  M3[merge_transfers] --> DRAFT
  M4[generate_club_index] --> CI

  %% Scan
  S1[scan_missing_players] --> SCAN

  %% Connections
  H --> M2
  PA --> M1
  T --> CTR
  TR --> M3
  MASTER --> M4
  MH --> S1
