intro:
  en: "Welcome to African Football Pulse — your daily source for African perspectives in the Premier League."
  sw: "Karibu kwenye African Football Pulse — chanzo chako cha kila siku cha habari kutoka Ligi Kuu ya Uingereza."
  ar: "مرحبًا بكم في African Football Pulse — مصدركم اليومي لآراء كرة القدم الإفريقية في الدوري الإنجليزي."

outro:
  en: "That’s all for today’s recap. Thanks for listening — and see you tomorrow on African Football Pulse."
  sw: "Hayo ndiyo kwa leo. Asante kwa kusikiliza — tukutane tena kesho kwenye African Football Pulse."
  ar: "هذا كل شيء لليوم. شكرًا لاستماعكم — نراكم غدًا في African Football Pulse."
