league: premier_league
sources:
  - name: guardian_football
    url: https://www.theguardian.com/football/rss
    active: true
  - name: bbc_football
    url: http://feeds.bbci.co.uk/sport/football/rss.xml
    active: true
  - name: sky_sports_premier_league
    url: https://www.skysports.com/rss/12040
    active: true
  - name: independent_football
    url: https://www.independent.co.uk/sport/football/rss
    active: true
  - name: epl
    url: http://www.football-news-views.co.uk/premier-league-rss.xml
    active: true
  - name: english_championship
    url: http://www.football-news-views.co.uk/championship-rss.xml
    active: true
  - name: liverpool_features
    url: https://www.liverpool.com/features/?service=rss
    active: true
  - name: liverpool_transfer
    url: https://www.liverpool.com/liverpool-fc-news/transfer-news?service=rss
    active: true
  - name: liverpool_schedule
    url: https://www.liverpool.com/schedule/?service=rss
    active: true
  - name: football_london_all
    url: https://www.football.london/?service=rss
    active: true
  - name: football_london_arsenal
    url: https://www.football.london/arsenal-fc/?service=rss
    active: true
  - name: football_london_chelsea
    url: https://www.football.london/chelsea-fc/?service=rss
    active: true
  - name: football_london_tottenham
    url: https://www.football.london/tottenham-hotspur-fc/?service=rss
    active: true
  - name: football_london_westham
    url: https://www.football.london/west-ham-united-fc/?service=rss
    active: true
  - name: soccerstats_english
    url: https://www.soccerstats247.com/DailyMatchFeed.aspx?langId=1
    active: true
  - name: eyefootball_news
    url: https://www.eyefootball.com/rss_news_main.xml
    active: true
  - name: eyefootball_transfers
    url: https://www.eyefootball.com/rss_news_transfers.xml
    active: true
