pods:
  PL_daily_africa_en:
    status: off
    leagues: ["premier_league"]
    langs: ["en"]
    role_map:
      news_anchor: "AK"
      expert: "JJK"
      storyteller: "AK"   # 👈 Lägg till denna
    publish:
      buzzsprout_podcast_id: 2538204
      buzzsprout_name: "African Football Pulse"
      language: "en"
      explicit: false

  test_patriks_podcast:
    status: on
    leagues: ["premier_league"]
    langs: ["en"]
    role_map:
      news_anchor: "AK"
      expert: "JJK"
      storyteller: "AK"   # 👈 Lägg till denna
    publish:
      buzzsprout_podcast_id: 2533393
      buzzsprout_name: "Patrik's Podcast"
      language: "en"
      explicit: false
