# config/produce_plan.yaml
version: 1
sections_library: "config/sections_library.yaml"

defaults:
  date: "{{today}}"
  league: "premier_league"
  lang: "en"
  write_latest: true
  personas_path: "config/personas.json"
  source: "guardian"
  news_base: "curated/news"
  out_base: "produce/out"

tasks:
  - section_code: "S.STATS.TOP_AFRICAN_PLAYERS"
    league: "premier_league"
    lang: "en"

    # Primär källa – bara för att produce_auto ska kunna bygga en första 'news' URL:
    source: "guardian_football"

    # Övriga källor att merga in (runnern hämtar dem automatiskt):
    extra_sources:
      - "bbc_football"
      - "independent_football"
      - "sky_sports_premier_league"

    config:
      top_african_players:
        top_n: 3
        news_window_hours: 48
        recency:
          half_life_hours: 24
