defaults:
  date: "{{today}}"
  league: premier_league
  personas_path: config/personas.json
  write_latest: true

tasks:
  - section_code: S.STATS.TOP_AFRICAN_PLAYERS
    source: bbc
  - section_code: S.NEWS.TOP3
    source: guardian
  - section_code: S.NEWS.CLUB_HIGHLIGHT
    source: skysports
  - section_code: S.OPINION.EXPERT_COMMENT
    source: bbc
  - section_code: S.OPINION.DUO_EXPERTS
    source: guardian
