defaults:
  date: "{{today}}"
  league: premier_league
  write_latest: true

tasks:
  - section_code: S.STATS.TOP_AFRICAN_PLAYERS
    args:
      - --league
      - premier_league
      - --outdir
      - sections
      - --write-latest
      - --news
      - curated/news/sky_sports_premier_league/premier_league/{{today}}/items.json
