# config/produce_plan.yaml
version: 1

# Var "runner" och modul för sektioner slås upp
sections_library: "config/sections_library.yaml"

# Standardvärden som kan ärvas av tasks
defaults:
  # Datum som mappas till <date> i blob-sökväg. "{{today}}" brukar hanteras i produce_auto.py.
  date: "{{today}}"

  # Liga/kanal (styr även väg i blob). Använd det ni redan använder i Collect.
  league: "premier_league"

  # Språk för rendering (sektionen växlar text lätt efter lang)
  lang: "en"

  # Skriv även "latest.json" för senaste körningen
  write_latest: true

  # (Valfritt) personasfil om ert producer förväntar sig den
  personas_path: "config/personas.json"

  # Primär nyhetskälla för S1 i MVP (håll en källa tills multi-source merge är på plats)
  source: "guardian"

  # Bas för var nyheter ligger i blob (produce_auto bygger full URL: curated/news/<source>/<league>/<date>/items.json)
  news_base: "curated/news"

  # Var output ska hamna relativt er standard (används av ert producer/assembler om tillämpligt)
  out_base: "produce/out"

# Körordning: lägg fler tasks nedan när ni vill bygga fler sektioner
tasks:
  # --- S1: Top African Players (nyhets-fallback, stats om injicerat i ctx['stats']) ---
  - section_code: "S.STATS.TOP_AFRICAN_PLAYERS"

    # Överskuggar defaults vid behov:
    league: "premier_league"
    lang: "en"
    source: "guardian"

    # (Valfritt) Direkt-override av news-URL om du vill peka på en viss fil:
    # news: "https://<account>.blob.core.windows.net/<container>/curated/news/guardian/premier_league/2025-08-31/items.json?<SAS>"

    # (Valfritt) Extra konfig som injiceras i ctx['config']['top_african_players']
    config:
      top_african_players:
        top_n: 3
        news_window_hours: 48
        recency:
          half_life_hours: 24
        # Tunas efter hand:
        # source_weights:
        #   guardian: 1.0
        #   bbc: 1.0
        #   sky: 0.9
        # event_keywords:
        #   hat-trick: 1.0
        #   brace: 0.8
        #   goal: 0.6
        #   assist: 0.4
        # top6_clubs:
        #   - Arsenal
        #   - Manchester City
        #   - Liverpool
        #   - Manchester United
        #   - Chelsea
        #   - Tottenham

  # Exempel på hur du kan lägga in fler (lämna kommenterade tills ni vill aktivera)
  # - section_code: "S.NEWS.TOP3"
  #   league: "premier_league"
  #   lang: "en"
  #   source: "guardian"

  # - section_code: "S.NEWS.CLUB_HIGHLIGHT"
  #   league: "premier_league"
  #   lang: "en"
  #   source: "guardian"
