roles:
  duo_experts:
    en:
      expert1: "ak"
      expert2: "jjk"
    sw:
      expert1: "ak"
      expert2: "jjk"
    ar:
      expert1: "oes"
      expert2: "kem"

  single_expert:
    en: "ak"
    sw: "ak"
    ar: "oes"

  storyteller:
    en: "ak"
    sw: "ak"
    ar: "oes"
