name: 11 Collect Transfers Bulk

on:
  workflow_dispatch:    # manuellt startbar
  schedule:
    - cron: "0 5 * * *"   # kör varje dag kl 05:00 UTC

jobs:
  collect-transfers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run collect_transfers_bulk
        env:
          SOCCERDATA_AUTH_KEY: ${{ secrets.SOCCERDATA_AUTH_KEY }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          AZURE_STORAGE_CONTAINER: afp
        run: |
          echo "🔄 Collecting transfers..."
          python -m src.collectors.collect_transfers_bulk | tee transfers_log.txt
          echo "✅ Done. See summary below:"
          echo "---- SUMMARY (last 20 lines) ----"
          tail -n 20 transfers_log.txt
