name: Build + Deploy Warehouse (ACA)

on:
  workflow_dispatch:   # Endast manuell körning från GitHub

env:
  AZURE_RESOURCE_GROUP: afp-rg
  ACA_JOB_NAME: afp-warehouse-job
  ACR_NAME: afpacr
  IMAGE_NAME: afp-runner
  IMAGE_TAG: gh-4
  SECRET_BLOB_SAS_NAME: blob-container-sas-url
  BLOB_PREFIX: warehouse/
  JOB_TYPE: warehouse

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (federated)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build image ref
        run: |
          echo "IMAGE_REF=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
          echo "IMAGE_REF=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

      - name: Login to ACR
        run: az acr login -n ${{ env.ACR_NAME }}

      - name: Docker build & push
        run: |
          docker build -t "$IMAGE_REF" -f Dockerfile .
          docker push "$IMAGE_REF"

      - name: Update ACA Job (image + env)
        run: |
          az containerapp job update \
            --name "${{ env.ACA_JOB_NAME }}" \
            --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" \
            --image "$IMAGE_REF" \
            --set-env-vars \
              JOB_TYPE="${{ env.JOB_TYPE }}" \
              BLOB_PREFIX="${{ env.BLOB_PREFIX }}" \
              BLOB_CONTAINER_SAS_URL=secretref:${{ env.SECRET_BLOB_SAS_NAME }}

      - name: Ensure Warehouse Schedule (06:00 UTC)
        run: |
          echo "🔄 Ensuring scheduled trigger for Warehouse (06:00 UTC)"
          JOB_ID=$(az containerapp job show \
            -n "${{ env.ACA_JOB_NAME }}" \
            -g "${{ env.AZURE_RESOURCE_GROUP }}" \
            --query id -o tsv)

          # Endast sätta trigger-fält – rör inte secrets
          az resource update \
            --ids $JOB_ID \
            --api-version 2023-05-01 \
            --set "properties.configuration.triggerType=Schedule" \
            --set "properties.configuration.scheduleTriggerConfig.cronExpression=0 6 * * *" \
            --set "properties.configuration.scheduleTriggerConfig.parallelism=1" \
            --set "properties.configuration.scheduleTriggerConfig.replicaCompletionCount=1"
