name: Build + Deploy Warehouse Player Stats (ACA)

on:
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: afp-rg
  ACA_JOB_NAME: afp-warehouse-player-stats-job
  ACR_NAME: afpacr
  IMAGE_NAME: afp-warehouse
  IMAGE_TAG: gh-1
  JOB_TYPE: src.warehouse.build_player_match_stats
  SECRET_BLOB_SAS_NAME: blob-container-sas-url

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (federated)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build image ref
        run: |
          echo "IMAGE_REF=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
          echo "IMAGE_REF=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

      - name: Login to ACR
        run: az acr login -n ${{ env.ACR_NAME }}

      - name: Docker build & push
        run: |
          docker build -t "$IMAGE_REF" -f Dockerfile .
          docker push "$IMAGE_REF"

      - name: Update ACA Job (image + env)
        run: |
          az containerapp job update \
            --name "${{ env.ACA_JOB_NAME }}" \
            --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" \
            --image "$IMAGE_REF" \
            --set-env-vars \
              JOB_TYPE="${{ env.JOB_TYPE }}" \
              AFP_OPENAI_SECRETKEY=${{ secrets.AFP_OPENAI_SECRETKEY }} \
              AZURE_STORAGE_ACCOUNT=${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              AZURE_CONTAINER=${{ secrets.AZURE_CONTAINER }} \
              AZURE_STORAGE_CONTAINER=${{ secrets.AZURE_CONTAINER }} \
              AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }} \
              AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }} \
              AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }} \
              AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }} \
              SOCCERDATA_AUTH_KEY=${{ secrets.SOCCERDATA_AUTH_KEY }} \
              BUZZSPROUT_API_TOKEN=${{ secrets.BUZZSPROUT_API_TOKEN }} \
              ELEVENLABS_API_KEY=${{ secrets.ELEVENLABS_API_KEY }} \
              BLOB_CONTAINER_SAS_URL=secretref:${{ env.SECRET_BLOB_SAS_NAME }}
