name: Build + Deploy Collect (ACA)

on:
  workflow_dispatch:

env:
  # ---- Hårdkodade standardvärden (ändra här vid behov) ----
  AZURE_RESOURCE_GROUP: afp-rg
  ACA_JOB_NAME: afp-collect-job
  ACR_NAME: afpacr
  IMAGE_NAME: afp-runner
  IMAGE_TAG: gh-4
  # hemligheter i ACA: referenser till KeyVault/Secrets i miljön
  SECRET_BLOB_SAS_NAME: blob-container-sas-url
  # env till din app
  BLOB_PREFIX: collector/
  JOB_TYPE: collect

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write        # krävs för federerad inloggning
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (federated)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build image ref
        run: |
          echo "IMAGE_REF=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
          echo "IMAGE_REF=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

      - name: Login to ACR
        run: az acr login -n ${{ env.ACR_NAME }}

      - name: Docker build & push
        run: |
          docker build -t "$IMAGE_REF" -f Dockerfile .
          docker push "$IMAGE_REF"

      - name: Update ACA Job (image + env)
        run: |
          az containerapp job update \
            --name "${{ env.ACA_JOB_NAME }}" \
            --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" \
            --image "$IMAGE_REF" \
            --set-env-vars \
              JOB_TYPE="${{ env.JOB_TYPE }}" \
              BLOB_PREFIX="${{ env.BLOB_PREFIX }}" \
              BLOB_CONTAINER_SAS_URL=secretref:${{ env.SECRET_BLOB_SAS_NAME }}

      - name: Start job run
        run: |
          az containerapp job start \
            --name "${{ env.ACA_JOB_NAME }}" \
            --resource-group "${{ env.AZURE_RESOURCE_GROUP }}"
