name: Build Player Stats

on:
  workflow_dispatch:
    inputs:
      player_id:
        description: "Player ID (ex. 61819)"
        required: true

jobs:
  build-player-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run build_player_stats
        env:
          AFP_OPENAI_SECRETKEY:    ${{ secrets.AFP_OPENAI_SECRETKEY }}
          AZURE_STORAGE_ACCOUNT:   ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_CONTAINER }}
          BLOB_CONTAINER_SAS_URL:  ${{ secrets.BLOB_CONTAINER_SAS_URL }}
          AZURE_CLIENT_ID:         ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_SUBSCRIPTION_ID:   ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID:         ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET:     ${{ secrets.AZURE_CLIENT_SECRET }}
        run: |
          echo "Container: $AZURE_STORAGE_CONTAINER"
          python -m src.tools.build_player_stats --player ${{ github.event.inputs.player_id }}
