name: Build Player Stats

on:
  workflow_dispatch:
    inputs:
      player_id:
        description: "Player ID (ex. 61819)"
        required: true
  schedule:
    - cron: "0 5 * * 1"   # kör varje måndag kl 05:00

jobs:
  build-player-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run build_player_stats
        run: |
          python -m src.tools.build_player_stats --player ${{ github.event.inputs.player_id || '61819' }}

      - name: Upload to Azure Blob
        run: |
          az storage blob upload-batch \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --destination $AZURE_CONTAINER/stats/players \
            --source stats/players \
            --overwrite true
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
