name: Build & Deploy Produce Job
on:
  workflow_dispatch:

env:
  IMAGE_NAME: afp-runner          # same image used by collect/produce; entrypoint picks JOB_TYPE
  IMAGE_TAG: ${{ github.sha }}    # immutable tag per commit

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Login to Azure using your existing SP JSON secret
      - name: Azure login (SP JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Ensure the Container Apps CLI extension is available (idempotent)
      - name: Ensure containerapp extension
        run: az extension add --name containerapp --upgrade -y

      # Login to your Azure Container Registry
      - name: ACR login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # Build & Push to ACR
      - name: Build & Push image
        env:
          IMAGE: ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        run: |
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # Update the Container Apps JOB to use the freshly pushed image
      - name: Update Container Apps Job image (produce)
        run: |
          az containerapp job update \
            --name afp-produce \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ env.IMAGE }}
