name: Build + Deploy Produce (ACA)

on:
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: afp-rg
  ACA_JOB_NAME: afp-produce-job
  ACR_NAME: afpacr
  IMAGE_NAME: afp-runner
  IMAGE_TAG: gh-4

  # hemligheter i ACA
  SECRET_BLOB_SAS_NAME: blob-container-sas-url

  # app-env
  JOB_TYPE: produce
  BLOB_PREFIX: collector/
  # valfritt: låt auto-mode köra utan args, eller avkommentera raden nedan:
  # JOB_ARGS: "--section S.STATS.TOP_AFRICAN_PLAYERS --league premier_league"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (federated)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build image ref
        run: echo "IMAGE_REF=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Login to ACR
        run: az acr login -n ${{ env.ACR_NAME }}

      - name: Docker build & push
        run: |
          docker build -t "$IMAGE_REF" -f Dockerfile .
          docker push "$IMAGE_REF"

      - name: Update ACA Job (image + env)
        run: |
          az containerapp job update \
            --name "${{ env.ACA_JOB_NAME }}" \
            --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" \
            --image "$IMAGE_REF" \
            --set-env-vars \
              JOB_TYPE="${{ env.JOB_TYPE }}" \
              BLOB_PREFIX="${{ env.BLOB_PREFIX }}" \
              BLOB_CONTAINER_SAS_URL=secretref:${{ env.SECRET_BLOB_SAS_NAME }} \
              $( [ -n "${{ env.JOB_ARGS }}" ] && echo JOB_ARGS="${{ env.JOB_ARGS }}" )

      - name: Start job run
        run: az containerapp job start --name "${{ env.ACA_JOB_NAME }}" --resource-group "${{ env.AZURE_RESOURCE_GROUP }}"
