name: Build + Deploy Orchestrator (ACA)

on:
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: afp-rg
  ACA_JOB_NAME: afp-orchestrator-job
  ACR_NAME: afpacr
  IMAGE_NAME: afp-orchestrator
  IMAGE_TAG: gh-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (federated)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build image ref
        run: |
          echo "IMAGE_REF=${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
          echo "IMAGE_REF=$IMAGE_REF"

      - name: Login to ACR
        run: az acr login -n ${{ env.ACR_NAME }}

      - name: Docker build & push
        run: |
          docker build -t "$IMAGE_REF" -f Dockerfile.orchestrator .
          docker push "$IMAGE_REF"

      - name: Update ACA Job (image)
        run: |
          az containerapp job update \
            --name "${{ env.ACA_JOB_NAME }}" \
            --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" \
            --image "$IMAGE_REF" \
            --trigger-type Schedule \
            --cron-expression "0 6 * * *"
