name: Extract Full Season

on:
  workflow_dispatch:
    inputs:
      season:
        description: "Season string, e.g. 2024-2025"
        required: true
        default: "2024-2025"
      with_api:
        description: "Fetch details via API (true/false)"
        required: false
        default: "false"

jobs:
  extract-fullseason:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests pyyaml azure-storage-blob

      - name: Run collect_extract_fullseason
        env:
          BLOB_CONTAINER_SAS_URL: ${{ secrets.BLOB_CONTAINER_SAS_URL }}
          SOCCERDATA_AUTH_KEY: ${{ secrets.SOCCERDATA_AUTH_KEY }}
        run: |
          SEASON="${{ github.event.inputs.season }}"
          WITH_API="${{ github.event.inputs.with_api }}"

          echo "Running extract for season=$SEASON, with_api=$WITH_API"

          if [ "$WITH_API" = "true" ]; then
            python -m src.collectors.collect_extract_fullseason \
              --config config/leagues.yaml \
              --season "$SEASON" \
              --with_api
          else
            python -m src.collectors.collect_extract_fullseason \
              --config config/leagues.yaml \
              --season "$SEASON"
          fi
