name: Collect Stats

on:
  workflow_dispatch:
    inputs:
      smoke:
        description: "Run in smoke mode (only 5 matches)"
        required: false
        default: "false"
  push:
    branches:
      - feature/stats

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml azure-storage-blob

      - name: Run collect_stats from config
        env:
          BLOB_CONTAINER_SAS_URL: ${{ secrets.BLOB_CONTAINER_SAS_URL }}
          SOCCERDATA_AUTH_KEY: ${{ secrets.SOCCERDATA_AUTH_KEY }}
        run: |
          python src/collectors/collect_stats.py \
            --config config/stats_feeds.yaml \
            $([[ "${{ github.event.inputs.smoke }}" == "true" ]] && echo "--smoke")
