name: Collect Weekly Stats and Matches

on:
  schedule:
    - cron: "0 5 * * 1"   # varje måndag kl 05:00 UTC
  workflow_dispatch:

jobs:
  collect-weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build collector image
        run: docker build -t afp-collector:latest .

      - name: Run collect_stats_weekly (create manifests)
        run: |
          docker run --rm \
            -e JOB_TYPE=src.collectors.collect_stats_weekly \
            -e SECRETS_FILE=/app/secrets/secret.json \
            -v ${{ github.workspace }}/secrets/secret.json:/app/secrets/secret.json \
            afp-collector:latest

      - name: Run collect_extract_weekly (create match files)
        run: |
          docker run --rm \
            -e JOB_TYPE=src.collectors.collect_extract_weekly \
            -e SECRETS_FILE=/app/secrets/secret.json \
            -v ${{ github.workspace }}/secrets/secret.json:/app/secrets/secret.json \
            afp-collector:latest

      - name: List uploaded manifests and matches
        run: |
          echo "Listing manifests and matches for today:"
          DATE=$(date -u +"%Y-%m-%d")
          az storage blob list \
            --account-name $AZURE_STORAGE_ACCOUNT \
            --container-name $AZURE_STORAGE_CONTAINER \
            --prefix stats/weekly/$DATE/ \
            --output table
