name: Collect League Metadata

on:
  workflow_dispatch:

jobs:
  collect-leagues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests azure-storage-blob
      - name: Run collect_leagues
        env:
          BLOB_CONTAINER_SAS_URL: ${{ secrets.BLOB_CONTAINER_SAS_URL }}
          SOCCERDATA_AUTH_KEY: ${{ secrets.SOCCERDATA_AUTH_KEY }}
        run: |
          python -m src.tools.collect_leagues
