name: Collect Weekly Stats

on:
  schedule:
    - cron: "0 6 * * MON"
  workflow_dispatch:
    inputs:
      league_id:
        description: "Numeric league_id"
        required: true
        default: "228"
      season:
        description: "Season string, e.g. 2024-2025"
        required: true
        default: "2024-2025"

jobs:
  collect-weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests azure-storage-blob

      - name: Run collect_stats_weekly
        env:
          BLOB_CONTAINER_SAS_URL: ${{ secrets.BLOB_CONTAINER_SAS_URL }}
          SOCCERDATA_AUTH_KEY: ${{ secrets.SOCCERDATA_AUTH_KEY }}
        run: |
          python -m src.collectors.collect_stats_weekly \
            --league_id "${{ github.event.inputs.league_id }}" \
            --season "${{ github.event.inputs.season }}"
