name: Collect Player Profile

on:
  workflow_dispatch:
    inputs:
      PLAYER_ID:
        description: "Player ID (SoccerData ID or AFRxxx, lämna tom för att köra alla)"
        required: false
        default: ""
      ALL:
        description: "Sätt till true för att köra alla spelare"
        required: false
        default: "false"

jobs:
  collect_player_profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 azure-storage-blob

      - name: Run collect_player_profiles
        working-directory: .
        env:
          SOCCERDATA_AUTH_KEY: ${{ secrets.SOCCERDATA_AUTH_KEY }}
          AZURE_STORAGE_CONTAINER: afp
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          BLOB_CONTAINER_SAS_URL: ${{ secrets.BLOB_CONTAINER_SAS_URL }}
        run: |
          if [ "${{ github.event.inputs.ALL }}" == "true" ]; then
            python -m src.tools.collect_player_profiles --all
          else
            python -m src.tools.collect_player_profiles --player-id "${{ github.event.inputs.PLAYER_ID }}"
          fi
