name: Collect League & Season Metadata

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Choose what to collect (leagues or seasons)"
        required: true
        default: "leagues"
      country_id:
        description: "Optional: Country ID (only used in leagues mode)"
        required: false
        default: ""
      league_id:
        description: "League ID (only used in seasons mode)"
        required: false
        default: ""

jobs:
  collect-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt

      - name: Run collect_leagues
        if: ${{ github.event.inputs.mode == 'leagues' }}
        env:
          BLOB_CONTAINER_SAS_URL: ${{ secrets.BLOB_CONTAINER_SAS_URL }}
          SOCCERDATA_AUTH_KEY: ${{ secrets.SOCCERDATA_AUTH_KEY }}
        run: |
          if [ -z "${{ github.event.inputs.country_id }}" ]; then
            python -m src.tools.collect_leagues
          else
            python -m src.tools.collect_leagues --country_id "${{ github.event.inputs.country_id }}"
          fi

      - name: Run collect_seasons
        if: ${{ github.event.inputs.mode == 'seasons' }}
        env:
          BLOB_CONTAINER_SAS_URL: ${{ secrets.BLOB_CONTAINER_SAS_URL }}
          SOCCERDATA_AUTH_KEY: ${{ secrets.SOCCERDATA_AUTH_KEY }}
        run: |
          if [ -z "${{ github.event.inputs.league_id }}" ]; then
            echo "ERROR: league_id must be set in seasons mode" && exit 1
          fi
          python -m src.tools.collect_seasons --league_id "${{ github.event.inputs.league_id }}"
