name: Collect Stats

on:
  push:
    branches:
      - feature/stats
  workflow_dispatch:
    inputs:
      smoke:
        description: "Run in smoke mode (only 5 matches)"
        required: false
        default: "false"

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install soccerdata pandas azure-storage-blob pyyaml

      - name: Run collect_stats from config
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
          SOCCERDATA_AUTH_KEY: ${{ secrets.SOCCERDATA_AUTH_KEY }}
        run: |
          python src/collectors/collect_stats.py \
            --config config/stats_feeds.yaml \
            $([[ "${{ github.event.inputs.smoke }}" == "true" ]] && echo "--smoke")
