name: Merge African Players

on:
  workflow_dispatch:

jobs:
  merge-african-players:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run merge_players_africa
        env:
          SOCCERDATA_AUTH_KEY: ${{ secrets.SOCCERDATA_AUTH_KEY }}
          AZURE_STORAGE_CONTAINER: afp
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          BLOB_CONTAINER_SAS_URL: ${{ secrets.BLOB_CONTAINER_SAS_URL }}
        run: |
          python - <<EOF
          from src.tools.merge_players_africa import merge_players_africa
          merge_players_africa(
              whitelist_path="players_africa.json",
              ids_path="player_ID.txt",
              season="2024-2025"
          )
          EOF
