name: publish
on:
  workflow_dispatch:
    inputs:
      date:
        description: 'YYYY-MM-DD'
        required: false
      league:
        description: 'league (e.g., epl)'
        required: false
        default: 'epl'
      lang:
        description: 'lang (e.g., en)'
        required: false
        default: 'en'
      title_override:
        description: 'Optional title override'
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests

      - name: Publish to Buzzsprout
        env:
          BUZZSPROUT_API_TOKEN: ${{ secrets.BUZZSPROUT_API_TOKEN }}
          BUZZSPROUT_PODCAST_ID: ${{ secrets.BUZZSPROUT_PODCAST_ID }}
          DATE: ${{ inputs.date }}
          LEAGUE: ${{ inputs.league }}
          LANG: ${{ inputs.lang }}
          TITLE_OVERRIDE: ${{ inputs.title_override }}
        run: |
          python -m src.publisher.buzzsprout
