name: S_01 Build Players Flat

on:
  workflow_dispatch:

jobs:
  build-players-flat:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # 👈 krävs för OIDC (azure/login@v2)
      contents: read     # 👈 behövs för checkout

    env:
      # 👇 Alla Azure-variabler som azure_blob.py behöver
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      # Om du istället använder SAS:
      # BLOB_CONTAINER_SAS_URL: ${{ secrets.BLOB_CONTAINER_SAS_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run build_players_flat
        run: |
          python -m src.warehouse.build_players_flat --season 2025-2026
