name: S_05 Build Matches & Events (Incremental)

on:
  workflow_dispatch:
    inputs:
      season:
        description: "Season to process (e.g. 2025-2026)"
        required: true
        default: "2025-2026"
      league:
        description: "League ID (e.g. 228 for Premier League)"
        required: true
        default: "228"

jobs:
  build-matches-events-incremental:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Docker image
        run: |
          docker build -t afp-warehouse:latest .

      - name: Run build_matches_events_flat
        run: |
          docker run --rm \
            -e JOB_TYPE=src.warehouse.build_matches_events_flat \
            -e SEASON=${{ github.event.inputs.season }} \
            -e LEAGUE=${{ github.event.inputs.league }} \
            -e SECRETS_FILE=/app/secrets/secret.json \
            -v ${{ github.workspace }}/secrets/secret.json:/app/secrets/secret.json \
            afp-warehouse:latest
