name: S_10 Build Match Performance Africa

on:
  workflow_dispatch:

jobs:
  build-match-performance-africa:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      AZURE_STORAGE_ACCOUNT:   ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_CONTAINER }}
      BLOB_CONTAINER_SAS_URL:  ${{ secrets.BLOB_CONTAINER_SAS_URL }}
      AZURE_CLIENT_ID:         ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID:         ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_SECRET:     ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run builder (match performance africa)
        run: |
          python -m src.warehouse.build_match_performance_africa --league 228 --season 2025-2026
