name: Debug SAS Token

on:
  workflow_dispatch:   # körs manuellt

env:
  STORAGE_ACCOUNT: afpstoragepilot
  CONTAINER_NAME: afp
  SAS_SECRET_NAME: BLOB_CONTAINER_SAS_URL

jobs:
  debug-sas:
    runs-on: ubuntu-latest
    steps:
      - name: Inspect SAS token
        run: |
          RAW_SAS="${{ secrets[env.SAS_SECRET_NAME] }}"
          echo "Secret length: ${#RAW_SAS}"
          echo "First 10 chars: ${RAW_SAS:0:10}"
          echo "Last 10 chars: ${RAW_SAS: -10}"
          if [[ "$RAW_SAS" == \?* ]]; then
            echo "⚠️ Secret starts with a ?"
          else
            echo "✅ Secret does NOT start with a ?"
          fi
