name: Test SAS Token (fixed)

on:
  workflow_dispatch:

env:
  STORAGE_ACCOUNT: afpstoragepilot
  CONTAINER_NAME: afp
  SAS_SECRET_NAME: BLOB_CONTAINER_SAS_URL

jobs:
  test-sas:
    runs-on: ubuntu-latest
    steps:
      - name: Extract SAS token from URL
        id: prep
        run: |
          RAW_SAS="${{ secrets[env.SAS_SECRET_NAME] }}"
          # Plocka bort allt fram till första "?"
          CLEAN_SAS="${RAW_SAS#*\?}"
          echo "CLEAN_SAS=$CLEAN_SAS" >> $GITHUB_ENV
          echo "Secret length: ${#CLEAN_SAS}"
          echo "First 10 chars: ${CLEAN_SAS:0:10}"
          echo "Last 10 chars: ${CLEAN_SAS: -10}"

      - name: Test blob list
        run: |
          echo "🔑 Testing SAS-token against container ${{ env.CONTAINER_NAME }}"
          az storage blob list \
            --account-name ${{ env.STORAGE_ACCOUNT }} \
            --container-name ${{ env.CONTAINER_NAME }} \
            --sas-token "$CLEAN_SAS" \
            --num-results 5 \
            --output table
