name: Test Blob Access

on:
  workflow_dispatch:   # körs manuellt

env:
  AZURE_RESOURCE_GROUP: afp-rg
  STORAGE_ACCOUNT: afpstoragepilot
  CONTAINER_NAME: afp
  SAS_SECRET_NAME: BLOB_CONTAINER_SAS_URL

jobs:
  test-blob:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Azure login (federated)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Test blob list
        run: |
          echo "🔑 Testing SAS-token against container ${{ env.CONTAINER_NAME }}"
          az storage blob list \
            --account-name ${{ env.STORAGE_ACCOUNT }} \
            --container-name ${{ env.CONTAINER_NAME }} \
            --sas-token "${{ secrets[env.SAS_SECRET_NAME] }}" \
            --num-results 5 \
            --output table
